import * as fs from "node:fs";
import * as path from "node:path";
import { parseDocFile, toTitleCase } from "./parse.js";
import type { DocsPage, DocsProject } from "./types.js";

/** Package machinery that sits alongside the content and is never a project. */
const NOT_A_PROJECT = new Set(["dist", "node_modules", ".turbo"]);

/** Markdown paths below `dir`, relative to it, extension stripped, slash-separated. */
function walk(dir: string, prefix = ""): string[] {
  const found: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith(".")) continue;
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      found.push(...walk(path.join(dir, entry.name), rel));
    } else if (entry.name.endsWith(".md")) {
      found.push(rel.replace(/\.md$/, ""));
    }
  }
  return found;
}

function isIndexPath(pagePath: string): boolean {
  const base = pagePath.split("/").at(-1)?.toLowerCase() ?? "";
  return base === "index" || base === "readme";
}

/**
 * Reads every markdown file under `contentRoot`, grouped by project — each
 * immediate subfolder is one project, and the first segment of a page's path
 * is its project.
 */
export function compileDocs(contentRoot: string): {
  projects: DocsProject[];
  pages: DocsPage[];
} {
  const projectSlugs = fs
    .readdirSync(contentRoot, { withFileTypes: true })
    .filter(
      (entry) =>
        entry.isDirectory() &&
        !entry.name.startsWith(".") &&
        !NOT_A_PROJECT.has(entry.name),
    )
    .map((entry) => entry.name)
    .sort();

  const pages: DocsPage[] = [];
  const projects: DocsProject[] = [];

  for (const slug of projectSlugs) {
    const projectDir = path.join(contentRoot, slug);
    const relPaths = walk(projectDir).sort();
    if (relPaths.length === 0) continue;

    const project: DocsProject = {
      slug,
      name: toTitleCase(slug),
      description: null,
    };

    for (const rel of relPaths) {
      const source = fs.readFileSync(
        path.join(projectDir, `${rel}.md`),
        "utf-8",
      );
      const parsed = parseDocFile(source, rel.split("/").at(-1)!);
      pages.push({ ...parsed, project: slug, path: `${slug}/${rel}` });

      // The project's own index page seeds its display name + description on
      // the docs landing page. A nested folder's index page doesn't.
      if (isIndexPath(rel) && !rel.includes("/")) {
        if (typeof parsed.frontmatter.name === "string") {
          project.name = parsed.frontmatter.name;
        }
        project.description = parsed.description;
      }
    }

    projects.push(project);
  }

  projects.sort((a, b) => a.name.localeCompare(b.name));
  pages.sort((a, b) => a.path.localeCompare(b.path));

  return { projects, pages };
}

/**
 * Writes the compiled content as an ESM module plus its declarations.
 *
 * The output is emitted directly rather than run through tsc, so the content
 * package needs no TypeScript toolchain — `docs/` stays markdown plus a
 * package.json, with none of this code sitting alongside it.
 */
export function emitDocsModule(contentRoot: string, outDir: string): number {
  const { projects, pages } = compileDocs(contentRoot);

  fs.mkdirSync(outDir, { recursive: true });

  fs.writeFileSync(
    path.join(outDir, "index.js"),
    `// GENERATED by @devdogsuga/docs-build — do not edit.
export const projects = ${JSON.stringify(projects, null, 2)};

export const pages = ${JSON.stringify(pages, null, 2)};
`,
    "utf-8",
  );

  fs.writeFileSync(
    path.join(outDir, "index.d.ts"),
    `// GENERATED by @devdogsuga/docs-build — do not edit.
import type { DocsPage, DocsProject } from "@devdogsuga/docs-build";

export declare const projects: DocsProject[];
export declare const pages: DocsPage[];

export type {
  DocHeading,
  DocsPage,
  DocsProject,
  ParsedDocFile,
} from "@devdogsuga/docs-build";
`,
    "utf-8",
  );

  return pages.length;
}
