allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
onlyBuiltDependencies:
  - esbuild
  - sharp
  - supabase
  - unrs-resolver
  - workerd
packages:
  - apps/*
  - packages/*
