/**
 * Ambient shim for `cloudflare:workers`, scoped to the Next/DOM-lib program
 * ONLY.
 *
 * `./index.ts` imports `env` from `cloudflare:workers` and is type-only
 * imported (via `~/lib/parsers/reconcileTerm.ts`'s `import type { db } from
 * "~/server/db"`) from `cloudflare/ScrapeWorkflow.ts`, so it is ALSO part of
 * `cloudflare/tsconfig.json`'s separate Workers-runtime program. That program
 * already has a real `declare module 'cloudflare:workers'` -- generated by
 * `wrangler types` into `cloudflare-env.d.ts`, reachable there via
 * `ScrapeWorkflow.ts`'s own `/// <reference path="../cloudflare-env.d.ts" />`
 * -- so this file must NOT be visible to that program, or the two ambient
 * declarations for the same module collide (`error TS2451: Cannot redeclare
 * block-scoped variable 'env'`).
 *
 * This file is deliberately unimported and untyped-referenced by anything:
 * it becomes part of a TypeScript program purely by glob-matching that
 * program's own `include`. The root tsconfig.json's `"**\/*.ts"` picks it up;
 * `cloudflare/tsconfig.json`'s `"**\/*.ts"` is rooted at `cloudflare/` and
 * never reaches into `src/`, so it does not. Do not add a triple-slash
 * reference to this file from anything under `cloudflare/`.
 *
 * Kept structural and minimal (just the one binding `./index.ts` reads) for
 * the same reason as `ScrapeWorkflow.ts`'s hand-rolled `WorkflowSentryEnv`:
 * importing the wrangler-generated `CloudflareEnv`/`Cloudflare.Env` type here
 * would mean importing `cloudflare-env.d.ts` into this DOM-lib program too,
 * merging in its Workers-runtime globals -- see `cloudflare/tsconfig.json`'s
 * comment for why those two collide.
 */
declare module "cloudflare:workers" {
  export const env: {
    HYPERDRIVE?: { readonly connectionString: string };
  };
}
