// GENERATED by scripts/generate-campus-map.ts — do not edit by hand.
// Map data © OpenStreetMap contributors, ODbL — openstreetmap.org/copyright
// Frame: lat 33.9441..33.9525, lon -83.3832..-83.3715, equirectangular, 480x415.

/** The map's viewBox — also what sizes its placeholder before it loads. */
export const VIEW = { w: 480, h: 415 };

/** Centroid of the DLW's footprint — where the Google/Apple Maps links drop their pin. */
export const DLW_CENTER = { lat: 33.948708, lon: -83.379511 };
