// GENERATED by scripts/generate-campus-map.ts — do not edit by hand.
// Map data © OpenStreetMap contributors, ODbL — openstreetmap.org/copyright
// Frame: lat 33.9372..33.9552, lon -83.3861..-83.3668, equirectangular, 480x540.

/** The map's viewBox — also what sizes its placeholder before it loads. */
export const VIEW = { w: 480, h: 540 };

/** Every building a meeting can name. The map highlights exactly one of them. */
export const BUILDING_KEYS = [
  "DLW",
  "Driftmier",
  "Plant Sciences",
  "Boyd",
  "MLC",
  "Science Learning Center",
  "Science Library",
  "Poultry Science",
  "Main Library",
  "Tate",
] as const;

export type BuildingKey = (typeof BUILDING_KEYS)[number];

/**
 * Each building's footprint centroid — where the Google/Apple Maps links drop
 * their pin. A coordinate rather than a place query because the DLW is too new
 * for either app to resolve by name, and a coordinate behaves the same for all
 * ten.
 */
export const BUILDING_CENTERS: Record<
  BuildingKey,
  { lat: number; lon: number }
> = {
  DLW: {
    lat: 33.948708,
    lon: -83.379511,
  },
  Driftmier: {
    lat: 33.93884,
    lon: -83.375119,
  },
  "Plant Sciences": {
    lat: 33.942406,
    lon: -83.375111,
  },
  Boyd: {
    lat: 33.94593,
    lon: -83.374975,
  },
  MLC: {
    lat: 33.951709,
    lon: -83.375806,
  },
  "Science Learning Center": {
    lat: 33.942755,
    lon: -83.376289,
  },
  "Science Library": {
    lat: 33.946064,
    lon: -83.375379,
  },
  "Poultry Science": {
    lat: 33.946707,
    lon: -83.37459,
  },
  "Main Library": {
    lat: 33.954022,
    lon: -83.373744,
  },
  Tate: {
    lat: 33.950516,
    lon: -83.375277,
  },
};
