export {
  ArrowSquareOutIcon,
  BookOpenIcon,
  BusIcon,
  CalendarDotsIcon,
  ChalkboardTeacherIcon,
  ChatCircleIcon,
  DiscordLogoIcon,
  DownloadSimpleIcon,
  EnvelopeSimpleIcon,
  FileTextIcon,
  GithubLogoIcon,
  GlobeIcon,
  HandshakeIcon,
  HashIcon,
  HouseIcon,
  InstagramLogoIcon,
  KeyIcon,
  LinkedinLogoIcon,
  LockIcon,
  MagnifyingGlassIcon,
  PauseIcon,
  PlayIcon,
  QrCodeIcon,
  ScalesIcon,
  RankingIcon,
  ScrollIcon,
  SealIcon,
  SealCheckIcon,
  ShieldIcon,
  ShieldWarningIcon,
  SirenIcon,
  StarIcon,
  TerminalWindowIcon,
  ToolboxIcon,
  TrophyIcon,
  UserIcon,
  UsersIcon,
  WrenchIcon,
} from "@phosphor-icons/react/ssr";

// The DevDogs apps' own marks, alongside the Phosphor set so a switcher tile,
// a docs mark or a menu row can name either kind and render it the same way.
export {
  DogDaysIcon,
  DogPackIcon,
} from "~/components/ProjectsSection/project-icons";
