export {
  ArrowSquareOutIcon,
  BookOpenIcon,
  CalendarDotsIcon,
  ChatCircleIcon,
  DiscordLogoIcon,
  EnvelopeSimpleIcon,
  FileTextIcon,
  GithubLogoIcon,
  GlobeIcon,
  HandshakeIcon,
  HashIcon,
  HouseIcon,
  InstagramLogoIcon,
  KeyIcon,
  LinkedinLogoIcon,
  LockIcon,
  MagnifyingGlassIcon,
  ScalesIcon,
  ScrollIcon,
  SealIcon,
  SealCheckIcon,
  ShieldIcon,
  ShieldWarningIcon,
  SirenIcon,
  UserIcon,
  UsersIcon,
} from "@phosphor-icons/react/ssr";
